name: CI

on:
  push:
  pull_request:

jobs:
  nix-build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-13, macos-12, macos-11]
        package: [dump-decls-lib, dump-decls-exe]
        nix_file: [build.ghc96.nix, build.ghc98.nix]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix-build ${{ matrix.package }}/${{ matrix.nix_file }}
      - name: Test run of 'dump-decls' executable
        if: ${{ matrix.package == 'dump-decls-exe' }}
        run: nix-shell --run '$(nix-build ${{ matrix.package }}/${{ matrix.nix_file }})/bin/dump-decls $(ghc-pkg list --simple-output --names-only)'
