name: CI

on:
  push:
  pull_request:

jobs:
  nix-build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix-build
      - name: Test run of 'dump-decls' executable
        run: nix-shell --run '$(nix-build)/bin/dump-decls $(ghc-pkg list --simple-output --names-only)'
